export default {
  login: 'khareemah',
  id: 41267322,
  node_id: 'MDQ6VXNlcjQxMjY3MzIy',
  avatar_url: 'https://avatars.githubusercontent.com/u/41267322?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/khareemah',
  html_url: 'https://github.com/khareemah',
  followers_url: 'https://api.github.com/users/khareemah/followers',
  following_url:
    'https://api.github.com/users/khareemah/following{/other_user}',
  gists_url: 'https://api.github.com/users/khareemah/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/khareemah/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/khareemah/subscriptions',
  organizations_url: 'https://api.github.com/users/khareemah/orgs',
  repos_url: 'https://api.github.com/users/khareemah/repos',
  events_url: 'https://api.github.com/users/khareemah/events{/privacy}',
  received_events_url: 'https://api.github.com/users/khareemah/received_events',
  type: 'User',
  site_admin: false,
  name: 'Oluwatosin Kareemat Ajimobi',
  company: null,
  blog: 'kareemah.netlify.app',
  location: 'Ibadan, Nigeria',
  email: null,
  hireable: null,
  bio: 'Frontend Developer, Student, HTML || CSS || JS || REACT',
  twitter_username: 'ola_reemah',
  public_repos: 50,
  public_gists: 0,
  followers: 7,
  following: 10,
  created_at: '2018-07-15T15:35:29Z',
  updated_at: '2022-01-31T11:55:01Z',
};
